RXR-550: bring 48-hour criteria to KDIGO staging definitions
InsightRX/clinPK pull request #23
Opened 2021-10-19 22:52 UTC by karawoo

Pulls KDIGO logic into its own function so that we can iterate over the timepoints to check that rises of >=0.3 mg/dl happen within a 48 hour window. A few tests needed to be updated based on this logic. We may need to update some tests on the insightrxr side as well, I haven't checked those yet.

While working on this I also found that we had a bug if age was NULL here:

https://github.com/InsightRX/clinPK/blob/a2e6ad00e1a84f68a7d3c1ed14e0b32d92696763/R/calc_aki_stage.R#L167

That line would evaluate to `logical(0)`, even if the other criteria (i.e. scr >= 4) were met. That is also fixed in this branch, and a new test has been added for it.

Please do pay close attention to the logic here. I think I captured the 48 hour restriction, but after all of our discussion I want to make extra sure that we've got this right.

2021-10-19 23:23 UTC, jasmineirx requested changes
a couple minor suggestions, otherwise approach lgtm

2021-10-19 23:23 UTC, jasmineirx commented on R/calc_aki_stage.R
> +    }
comparing a value to a float could result in floating point precision issues, which I ran into when implementing my own version of this logic. we should either use `all.equal` or round the value being compared to 0.3 and 1.5

2021-10-19 23:23 UTC, jasmineirx commented on R/calc_aki_stage.R
> +    if (scr / baseline_scr >= 1.5 | (i > 1 && scr - min(scr_last_48h) >= 0.3)) {
```suggestion
    if (scr / baseline_scr >= 1.5 || (i > 1 && scr - min(scr_last_48h) >= 0.3)) {
```
I think this ought to also be double pipes since we do not wish this to be vectorized.

2021-10-19 23:23 UTC, jasmineirx commented on R/calc_aki_stage.R
> +    }
```suggestion
    if (scr / baseline_scr >= 3 || scr >= 4 || isTRUE(dat$egfr[i] < 35 & age < 18)) {
      stage[i] <- 3
    }
```
same comment as above; previously we used vectorization but we've switched to a for loop so I believe this should use double pipes.

2021-10-19 23:23 UTC, jasmineirx commented on R/calc_aki_stage.R
> +    if (scr / baseline_scr >= 1.5 | (i > 1 && scr - min(scr_last_48h) >= 0.3)) {
We will produce a warning if scr_last_48h is of length 0 (i.e., there are no scr in last 48 hrs). 

``` r
dat <- data.frame(
  scr = c(1.5, 1.5, 1.9),
  t = c(-1, 0, 55),
  baseline_scr_diff = c(0, 0, 0.4),
  egfr = c(100, 100, 60)
)

clinPK:::kdigo_stage(dat, 1.5, 50)
#> Warning in min(scr_last_48h): no non-missing arguments to min; returning Inf
#> [1] NA NA NA
```

<sup>Created on 2021-10-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
(note that in the example above, no AKI is detected as desired, it is only the warning that is produced that we should avoid, the logic is functioning correctly)

perhaps rather than the `i > 1` condition we want to try `length(scr_last_48h) > 0`?

2021-10-20 00:19 UTC, karawoo commented on R/calc_aki_stage.R
> +    if (scr / baseline_scr >= 1.5 | (i > 1 && scr - min(scr_last_48h) >= 0.3)) {
Good catch, thanks!

2021-10-20 00:35 UTC, karawoo commented on R/calc_aki_stage.R
> +    }
👍  I've added a new operator to do the comparison with a little wiggle room for floating point issues

2021-10-20 00:46 UTC, jasmineirx approved these changes
lgtm, clean solution to the floating point precision problem.

2021-10-20 00:47 UTC, jasmineirx commented
Looks like CI wants x and y to be documented for `%>=%`?

2021-10-20 16:27 UTC, karawoo commented
TIL how roxygen translates `%` when creating a file name 🍇 
![Screen Shot 2021-10-20 at 9 27 14 AM](https://user-images.githubusercontent.com/4452678/138133182-92591135-489c-4043-b75e-36810eae3da0.png)
.

2021-10-20 17:45 UTC, karawoo commented on R/calc_aki_stage.R
> +    # i > 1, since otherwise we don't have any prior timepoints to compare to.
👍  good catch, made the changes locally so I could fix a small typo

2021-10-20 17:48 UTC, karawoo commented on R/utils.R
> +`%>=%` <- function(x, y) {
I thought that might be useful, but irxtools is currently private and clinPK is public, so if clinPK is going to take on that dependency we'd need to make irxtools public as well. That seemed like a bigger discussion, maybe we can revisit it separately? It wouldn't be hard to update this later if we do decide to move it to a different package.

2021-10-20 17:50 UTC, merged