update calc_creat for adults with NHANES regression
InsightRX/clinPK pull request #62
Opened 2024-06-18 18:26 UTC by JordanBrooks33

Added my regression model to calc_creat() and updated tests. Would love recommendations on how to handle warnings for height and weight as these were historically not required by this function. Since they were weaker effects than Age and Sex, I think imputing the median is fine in cases where they are not available. Happy to alter.

2024-06-18 21:06 UTC, jasmineirx reviewed
I'm excited to add this new functionality! 

I think best practices would be to add a new argument for `method`, i.e.,

```r
method = c("Johanssen", "NHANES"),
```

then one the the early lines in the function can be
```
method <- match.arg(method)
```
which means if no method is supplied, the old logic is used, and only accepted methods are allowed.

we can then change the warnings accordingly:

```r
if (is.null(weight) && method == "NHANES") stop("Weight is required)
```
etc

The body of the function would also have to be updated to that both the old and the new logic is used depending on method. We might want to consider putting it in functions and calling the right calculation method based on a `switch` statement. see `calc_ffm` for an example.

I also suggest using the variable names `weight` and `height`, since that is consistent with what we use elsewhere in the package

2024-06-18 22:24 UTC, roninsightrx requested changes
agree with Jasmine's comments. Few minor add'l things

2024-06-18 22:24 UTC, roninsightrx commented on R/calc_creat.R
> +#' specified.
Can we put the core of the linear regression fit code that was used here in the description, for reproducibility? I guess was sth like

```
lm(creat ~ weight + height + sex, data = NHANES)
```
Or if you split it up in separate functions like Jasmine suggested then add it there.

2024-06-18 22:24 UTC, roninsightrx commented on R/calc_creat.R
> +    height <-ifelse(is.null(ht),165,ht)
spacing
```suggestion
    weight <- ifelse(is.null(wt), 75, wt)
    height <- ifelse(is.null(ht), 165, ht)
```

2024-06-18 22:24 UTC, roninsightrx commented on tests/testthat/test_calc_creat.R
> +    suppressWarnings(calc_creat(
if we expect and intended to have a warning, we should use `expect_warning()`. That will also suppress it, but test for it at the same time.

2024-06-19 00:49 UTC, JordanBrooks33 commented
Okay this all makes sense. I have altered the logic to include an adult_method specification.  In this way children and adolescents are handled the same way; however, it will default to the historic johanssen flat scr method for adults.

2024-06-26 18:51 UTC, jasmineirx requested changes
Thanks for refactoring. This looks great, and it's very readable. I have just a couple white spacing requests to bring this in line with the [tidyverse style guide](https://style.tidyverse.org/). There's also a couple behaviors we are not currently testing that we should. Please see the `expect_error` function.

2024-06-26 18:51 UTC, jasmineirx commented on R/calc_creat.R
> +      adult_method=adult_method
```suggestion
      adult_method = adult_method
```

2024-06-26 18:51 UTC, jasmineirx commented on R/calc_creat.R
> +      adult_method=adult_method
```suggestion
      adult_method = adult_method
```

2024-06-26 18:51 UTC, jasmineirx commented on R/calc_creat.R
> +  calc_creat_johanssen <- function(age, sex, adult_method) {
```suggestion
  ))
  
  calc_creat_johanssen <- function(age, sex, adult_method) {
```

2024-06-26 18:51 UTC, jasmineirx commented on R/calc_creat.R
> +    scr[sel1]   <- 9.5471 * age[sel1] - 87.847
```suggestion
    scr[sel1] <- 9.5471 * age[sel1] - 87.847
```

2024-06-26 18:51 UTC, jasmineirx commented on tests/testthat/test_calc_creat.R
> +
we should also test for appropriate error handling if age/sex/weight/height not supplied.

2024-06-26 18:51 UTC, jasmineirx commented on R/calc_creat.R
> +  calc_creat_brooks <- function(age, sex, weight, height, adult_method) {
```suggestion
  }
  
  calc_creat_brooks <- function(age, sex, weight, height, adult_method) {
```

2024-06-26 18:51 UTC, jasmineirx commented on R/calc_creat.R
> +    method = tolower(adult_method)
returning `method` is a new behavior and we should add a test for this too (and for unit)

2024-07-08 22:53 UTC, jasmineirx requested changes
something odd seems to have happened in this commit, where we are now defining the helper functions within the scope of the main function. We should instead define these functions outside of the function (as they were before)

2024-07-08 23:26 UTC, roninsightrx commented on R/calc_creat.R
> +#' data and takes into account sex, age, weight, and height. Equation: lm(SCr~Age+Sex+Weight+Height, data=NHANES)
Nitpick, for proper rendering in help:
```suggestion
#' data and takes into account sex, age, weight, and height. 
Equation: `lm(SCr~Age+Sex+Weight+Height, data=NHANES)`
```

2024-07-08 23:27 UTC, roninsightrx approved these changes
if you move the sub-function out of main function it looks good to me.

2024-07-09 14:07 UTC, jasmineirx commented
One last step, sorry that I just caught it. You need to run the command `devtools:document()` in order to render the new documentation you added. This will create a 'md' file, which you will need to commit and push up!

2024-07-09 17:08 UTC, JordanBrooks33 commented
> One last step, sorry that I just caught it. You need to run the command `devtools:document()` in order to render the new documentation you added. This will create a 'md' file, which you will need to commit and push up!

Nice catch! I have run the code and committed/pushed up the new documentation. I have not done this before, so just to double check -> in running the line above it updated the Description doc and created 2 new .rd docs in the man/ directory. Is this what was expected?

2024-07-09 17:18 UTC, jasmineirx approved these changes
lgtm! nice work :)

2024-07-09 17:49 UTC, merged